/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "on-tertiary-fixed": "#001551",
        "outline": "#926e69",
        "secondary-fixed-dim": "#c8c6c0",
        "inverse-primary": "#ffb4a8",
        "on-secondary-fixed": "#1b1c18",
        "on-tertiary-container": "#dde1ff",
        "on-primary-container": "#ffdbd5",
        "on-surface": "#1d1b19",
        "tertiary": "#003ec3",
        "on-secondary-container": "#63635d",
        "inverse-surface": "#32302d",
        "inverse-on-surface": "#f6f0eb",
        "surface-dim": "#ded9d4",
        "surface": "#fef8f3",
        "on-error": "#ffffff",
        "secondary-container": "#e1e0d9",
        "on-primary-fixed": "#410000",
        "on-background": "#1d1b19",
        "surface-container-high": "#ede7e2",
        "surface-container-lowest": "#ffffff",
        "error": "#ba1a1a",
        "surface-container": "#f3ede8",
        "on-primary": "#ffffff",
        "on-surface-variant": "#5e3f3a",
        "error-container": "#ffdad6",
        "on-tertiary": "#ffffff",
        "tertiary-fixed-dim": "#b7c4ff",
        "primary": "#cd0000",
        "secondary-fixed": "#e4e2dc",
        "surface-variant": "#e7e1dd",
        "tertiary-container": "#0052fa",
        "surface-container-highest": "#e7e1dd",
        "outline-variant": "#e8bdb6",
        "surface-bright": "#fef8f3",
        "surface-container-low": "#f8f3ed",
        "on-secondary": "#ffffff",
        "primary-fixed": "#ffdad4",
        "tertiary-fixed": "#dce1ff",
        "primary-container": "#cd0000",
        "on-secondary-fixed-variant": "#474742",
        "surface-tint": "#c00000",
        "on-tertiary-fixed-variant": "#0039b4",
        "background": "#efede6",
        "primary-fixed-dim": "#ffb4a8",
        "on-error-container": "#93000a",
        "secondary": "#5f5f59",
        "on-primary-fixed-variant": "#930000"
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      "spacing": {
        "gutter": "24px",
        "margin-lg": "64px",
        "margin-sm": "16px",
        "margin-md": "32px",
        "container-max": "1280px",
        "unit": "4px",
        "margin-desktop": "64px",
        "margin-mobile": "20px",
        "section-gap": "80px"
      },
      "fontFamily": {
        "label-sm": ["var(--font-oswald)", "sans-serif"],
        "headline-md": ["var(--font-oswald)", "sans-serif"],
        "display-lg": ["var(--font-oswald)", "sans-serif"],
        "headline-lg-mobile": ["var(--font-oswald)", "sans-serif"],
        "body-lg": ["var(--font-chivo)", "sans-serif"],
        "body-md": ["var(--font-chivo)", "sans-serif"],
        "label-lg": ["var(--font-oswald)", "sans-serif"],
        "headline-lg": ["var(--font-oswald)", "sans-serif"],
        "display-accent": ["var(--font-playfair-display)", "serif"]
      },
      "fontSize": {
        "label-sm": ["12px", { "lineHeight": "16px", "fontWeight": "500", "letterSpacing": "0.05em" }],
        "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "display-lg": ["72px", { "lineHeight": "80px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "headline-lg-mobile": ["32px", { "lineHeight": "40px", "fontWeight": "700" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "label-lg": ["14px", { "lineHeight": "20px", "letterSpacing": "0.05em", "fontWeight": "600" }],
        "headline-lg": ["48px", { "lineHeight": "56px", "fontWeight": "700" }],
        "display-accent": ["64px", { "lineHeight": "72px", "fontWeight": "400" }]
      }
    },
  },
  plugins: [],
}
